from django.db import models

class Sighting(models.Model):
    latitude = models.DecimalField('Latitude', max_digits =  10, decimal_places = 8)
    longitude = models.DecimalField('Longitude', max_digits = 10, decimal_places = 8) 
    unique_squirrel_id = models.CharField('Unique Squirrel ID', max_length = 200)
    shift = models.CharField('Shift', max_length = 200)
    date =  models.CharField('Date', max_length = 200)
    age = models.CharField('Age', max_length = 200)
    primary_fur_color = models.CharField('Primary Fur Color', max_length = 200)
    location = models.CharField('Location', max_length = 200)
    specific_location = models.CharField('Specific Location', max_length = 200)
    running = models.CharField('Running', max_length = 200)
    chasing = models.CharField('Chasing', max_length = 200)
    climbing = models.CharField('Climbing', max_length = 200)
    eating = models.CharField('Eating', max_length = 200)
    foraging = models.CharField('Foraging', max_length = 200)
    other_activities = models.CharField('Other Activities', max_length = 200)
    kuks = models.CharField('Kuks', max_length = 200)
    quaas = models.CharField('Quaas', max_length = 200)
    moans = models.CharField('Moans', max_length = 200)
    tail_flags = models.CharField('Tail flags', max_length = 200)
    tail_twitches = models.CharField('Tail twitches', max_length = 200)
    approaches = models.CharField('Approaches', max_length = 200)
    indifferent = models.CharField('Indifferent', max_length = 200)
    runs_from = models.CharField('Runs from', max_length = 200)
